# Generated by Django 5.1.3 on 2024-11-26 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "title_proposals",
                    models.CharField(
                        max_length=100, verbose_name="Заголовка Предложений"
                    ),
                ),
                (
                    "title_proposals_2",
                    models.CharField(max_length=100, verbose_name="Заголовка Школы"),
                ),
                (
                    "descriptions_proposals",
                    ckeditor.fields.RichTextField(verbose_name="Описание Предложения"),
                ),
                (
                    "title_teahers",
                    models.CharField(max_length=155, verbose_name="Заголовка Учильки"),
                ),
                (
                    "title_courses",
                    models.CharField(max_length=155, verbose_name="Заголовка Курсов"),
                ),
                (
                    "descriptions_courses",
                    ckeditor.fields.RichTextField(verbose_name="Описание курсов"),
                ),
                (
                    "title_available",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Доступности"
                    ),
                ),
                (
                    "title_price",
                    models.CharField(max_length=155, verbose_name="Заголовка Цены"),
                ),
                (
                    "title_suggestion",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Предположение"
                    ),
                ),
                (
                    "title_events",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Мероприятий"
                    ),
                ),
                (
                    "title_recommendations",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка рекомендации"
                    ),
                ),
                (
                    "title_study",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка исследования"
                    ),
                ),
                (
                    "title_online_lessons",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Онлайн урока"
                    ),
                ),
                (
                    "title_Education",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Образование"
                    ),
                ),
                (
                    "title_details_info",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Детального просмотра"
                    ),
                ),
                (
                    "descriptions_details",
                    ckeditor.fields.RichTextField(
                        verbose_name="Описание Детального просмотра"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройки Главной страницы",
            },
        ),
    ]
