# Generated by Django 5.1.3 on 2024-11-27 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_image_alter_settings_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="KikoUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("image", models.ImageField(upload_to="kiko/", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Обновленный Kiko",
            },
        ),
    ]
