# Generated by Django 5.1.3 on 2024-11-27 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_kikoupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceKiko",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "imgae",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="price_kiko/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "details",
                    models.CharField(max_length=100, verbose_name="Просмотры детально"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Художественный класс", "Художественный класс"),
                            ("География", "География"),
                            ("Письмо", "Письмо"),
                        ],
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Цены на Kiko",
            },
        ),
    ]
