# Generated by Django 5.1.3 on 2024-11-28 08:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_offers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("image", models.ImageField(upload_to="contact/", verbose_name="Фото")),
                (
                    "title_contact",
                    models.CharField(max_length=155, verbose_name="Заголовка"),
                ),
                (
                    "title_contact_2",
                    models.CharField(max_length=155, verbose_name="Заголовка - 2"),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "title_books",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Книги предоставлены"
                    ),
                ),
                (
                    "descriptions_books",
                    ckeditor.fields.RichTextField(
                        verbose_name="Описание Книги предоставлены"
                    ),
                ),
                (
                    "image_books",
                    models.ImageField(upload_to="contact", verbose_name="Фото"),
                ),
                (
                    "title_computer",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Компьютерный зал "
                    ),
                ),
                (
                    "descriptions_computer",
                    ckeditor.fields.RichTextField(
                        verbose_name="Описание Компьютерный зал"
                    ),
                ),
                (
                    "image_computer",
                    models.ImageField(upload_to="contact", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name_plural": "Наши контакты",
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("message", ckeditor.fields.RichTextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Форма контакта",
            },
        ),
    ]
