# Generated by Django 5.1.3 on 2024-11-28 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_contact_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("image", models.ImageField(upload_to="about", verbose_name="Фото")),
                (
                    "title_origin",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка происхождение"
                    ),
                ),
                (
                    "title_choice",
                    models.CharField(max_length=155, verbose_name="Заголовка Выбара"),
                ),
                (
                    "title_lessons",
                    models.CharField(max_length=155, verbose_name="Заголовка Урока"),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание Урока"),
                ),
            ],
            options={
                "verbose_name_plural": "О нас",
            },
        ),
    ]
