# Generated by Django 5.1.3 on 2024-11-28 15:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0008_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="descriptions_about",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Описание о нас "
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="image_abotu",
            field=models.ImageField(
                default=1, upload_to="about/about", verbose_name="Фото"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="title_about",
            field=models.CharField(
                default=11, max_length=155, verbose_name="Заголовка о нас"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="title_about2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка о нас 2"
            ),
            preserve_default=False,
        ),
    ]
