# Generated by Django 5.1.3 on 2024-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    models.CharField(max_length=155, verbose_name="Описание"),
                ),
                ("static", models.IntegerField(verbose_name="Статистика")),
            ],
            options={
                "verbose_name_plural": "Статистика",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name_plural": "Страница Галлерия"},
        ),
        migrations.AddField(
            model_name="gallery",
            name="image_static",
            field=models.ImageField(
                default=11, upload_to="static/", verbose_name="Фото"
            ),
            preserve_default=False,
        ),
    ]
