# Generated by Django 5.1.3 on 2024-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0012_statistic_alter_gallery_options_gallery_image_static"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="image", verbose_name="Фото 1")),
                ("image2", models.ImageField(upload_to="image", verbose_name="Фото 2")),
            ],
            options={
                "verbose_name_plural": "Фото",
            },
        ),
    ]
