# Generated by Django 5.1.3 on 2024-11-29 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0013_imagepages"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPynkt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="Пункты Галлерий", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name_plural": "Пункты Галлерий",
            },
        ),
    ]
