# Generated by Django 5.1.3 on 2024-11-29 10:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_gallerypynkt"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("image", models.ImageField(upload_to="news", verbose_name="Фото")),
                (
                    "title_news",
                    models.CharField(max_length=155, verbose_name="Заголовка Новостей"),
                ),
                (
                    "title_tuned",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка настроенный"
                    ),
                ),
                (
                    "title_tuned2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка под настроенный"
                    ),
                ),
                (
                    "descriptions_tuned",
                    ckeditor.fields.RichTextField(verbose_name="Описание настроенный"),
                ),
                ("image1", models.ImageField(upload_to="news", verbose_name="Фото")),
                ("image2", models.ImageField(upload_to="news", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Новости",
            },
        ),
    ]
