# Generated by Django 5.1.3 on 2024-11-29 11:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0016_news_image_back"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("title2", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name_plural": "Параграф новостей",
            },
        ),
    ]
