# Generated by Django 5.1.3 on 2024-11-29 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0017_newsparagraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("image", models.ImageField(upload_to="shop", verbose_name="Фото")),
                (
                    "title_share",
                    models.CharField(max_length=155, verbose_name="Заголовка Акций"),
                ),
                (
                    "title_share2",
                    models.CharField(max_length=155, verbose_name="Заголовка Акций 2"),
                ),
            ],
            options={
                "verbose_name_plural": "Магазин",
            },
        ),
    ]
