# Generated by Django 5.1.3 on 2024-12-02 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0026_galleryindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryindex",
            name="descriptions2",
            field=ckeditor.fields.RichTextField(verbose_name="Описание 2"),
        ),
    ]
