# Generated by Django 5.1.3 on 2024-12-02 09:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0027_alter_galleryindex_descriptions2"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="descriptions_about_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание о нас "
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="descriptions_about_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание о нас "
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Урока"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Урока"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_about2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас 2"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_about2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас 2"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_about_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_about_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_choice_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Выбара"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_choice_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Выбара"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_lessons_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Урока"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_lessons_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Урока"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_origin_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка происхождение"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_origin_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка происхождение"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="plus1_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Плюсы 1 "),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="plus1_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Плюсы 1 "),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="plus2_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Плюсы 2 "),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="plus2_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Плюсы 2 "),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="aboutpynkt",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_books_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Книги предоставлены"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_books_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Книги предоставлены"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_computer_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Компьютерный зал"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_computer_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Компьютерный зал"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contact",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_books_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Книги предоставлены"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_books_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Книги предоставлены"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_computer_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Компьютерный зал "
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_computer_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Компьютерный зал "
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_contact_2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка - 2"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_contact_2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка - 2"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_contact_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_contact_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="descriptions_discounts_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="descriptions_discounts_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_Discounts_Available_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Доступные скидки"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_Discounts_Available_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Доступные скидки"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_discounts_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка скидки"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_discounts_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка скидки"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_gellary_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_gellary_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="descriptions2_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание 2"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="descriptions2_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание 2"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_1_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_1_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_2_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_2_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="galleryindex",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallerypynkt",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="gallerypynkt",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="gallerypynkt",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="gallerypynkt",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="news",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="descriptions_tuned_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание настроенный"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="descriptions_tuned_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание настроенный"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_news_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Новостей"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_news_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Новостей"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tuned2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка под настроенный"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tuned2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка под настроенный"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tuned_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка настроенный"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tuned_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка настроенный"
            ),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="title2_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="title2_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="newsparagraph",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="offers",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="offers",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="offers",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="offers",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="priceblog",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="priceblog",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="details_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Просмотры детально"
            ),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="details_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Просмотры детально"
            ),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="pricekiko",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="priceshop",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="priceshop",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_courses_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание курсов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_courses_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание курсов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_details_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Детального просмотра"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_details_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Детального просмотра"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_proposals_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Предложения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_proposals_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Предложения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_Education_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Образование"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_Education_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Образование"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_available_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Доступности"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_available_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Доступности"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_courses_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Курсов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_courses_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Курсов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_details_info_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Детального просмотра"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_details_info_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Детального просмотра"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_events_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Мероприятий"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_events_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Мероприятий"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_online_lessons_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Онлайн урока"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_online_lessons_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Онлайн урока"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_price_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Цены"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_price_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Цены"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_proposals_2_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Заголовка Школы"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_proposals_2_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Заголовка Школы"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_proposals_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Заголовка Предложений"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_proposals_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Заголовка Предложений"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_recommendations_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_recommendations_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_study_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка исследования"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_study_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка исследования"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_suggestion_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Предположение"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_suggestion_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Предположение"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_teahers_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Учильки"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_teahers_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Учильки"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="shop",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_share2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Акций 2"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_share2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Акций 2"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_share_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Акций"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_share_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Акций"
            ),
        ),
        migrations.AddField(
            model_name="shopblog",
            name="title2_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="shopblog",
            name="title2_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 2"
            ),
        ),
        migrations.AddField(
            model_name="shopblog",
            name="title_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 1"
            ),
        ),
        migrations.AddField(
            model_name="shopblog",
            name="title_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка 1"
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="descriptions_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="statistic",
            name="descriptions_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="statistic",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="statistic",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
    ]
