# Generated by Django 5.1.3 on 2024-12-02 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0028_about_descriptions_about_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricekiko",
            old_name="imgae",
            new_name="image",
        ),
    ]
